Rails.application.routes.draw do
	root 'static_pages#home'
  	get '/help', to: 'static_pages#help' 
 	  get '/contact', to: 'static_pages#contact'
  	get '/about', to: 'static_pages#about'
  	get '/backup', to: 'static_pages#backup'
# Add class
  	get '/diskregu', to: 'static_pages#diskregu'
  	get '/diskmain', to: 'static_pages#diskmain'
  	get '/devregu', to: 'static_pages#devregu'
  	get '/internet', to: 'static_pages#internet'
  	get '/edit', to: 'static_pages#edit'
  	get '/trans', to: 'static_pages#trans'
  	get '/fileregu', to: 'static_pages#fileregu'
  	get '/sysregu', to: 'static_pages#sysregu'
  	get '/sysconf', to: 'static_pages#sysconf'
# Add elements
	#backup
  	get '/compress', to: 'static_pages#compress'
  	get '/bzip2', to: 'static_pages#bzip2'
  	get '/bunzip2', to: 'static_pages#bunzip2'
  	get '/ar', to: 'static_pages#ar'
  	get '/bzip2recover', to: 'static_pages#bzip2recover'
  	get '/unarj', to: 'static_pages#unarj'
  	get '/tar', to: 'static_pages#tar'
  	get '/gzexe', to: 'static_pages#gzexe'
  	get '/uudecode', to: 'static_pages#compress'
  	get '/unzip', to: 'static_pages#unzip'
  	get '/uuencode', to: 'static_pages#uuencode'
  	get '/zipinfo', to: 'static_pages#zipinfo'
  	get '/zip', to: 'static_pages#zip'
  	get '/restore', to: 'static_pages#restore'
  	get '/dump', to: 'static_pages#dump'
  	get '/cpio', to: 'static_pages#cpio'
  	get '/gunzip', to: 'static_pages#gunzip'
  	get '/lha', to: 'static_pages#lha'
  	get '/gzip', to: 'static_pages#gzip'
  #trans
    get '/bye', to: 'static_pages#bye'
    get '/ftp', to: 'static_pages#ftp'
    get '/ftpcount', to: 'static_pages#ftpcount'
    get '/ftpshut', to: 'static_pages#ftpshut'
    get '/ftpwho', to: 'static_pages#ftpwho'
    get '/lpd', to: 'static_pages#lpd'
    get '/lpq', to: 'static_pages#lpq'
    get '/lpr', to: 'static_pages#lpr'
    get '/lprm', to: 'static_pages#lprm'
    get '/ncftp', to: 'static_pages#ncftp'
    get '/tftp', to: 'static_pages#tftp'
    get '/uucico', to: 'static_pages#uucico'
    get '/uucp', to: 'static_pages#uucp'
    get '/uupick', to: 'static_pages#uupick'
    get '/uuto', to: 'static_pages#uuto'
  #edit
    get '/col', to: 'static_pages#col'
    get '/colrm', to: 'static_pages#colrm'
    get '/comm', to: 'static_pages#comm'
    get '/csplit', to: 'static_pages#csplit'
    get '/ed', to: 'static_pages#ed'
    get '/egrep', to: 'static_pages#egrep'
    get '/ex', to: 'static_pages#ex'
    get '/expr', to: 'static_pages#expr'
    get '/fgrep', to: 'static_pages#fgrep'
    get '/fmt', to: 'static_pages#fmt'
    get '/fold', to: 'static_pages#fold'
    get '/grep', to: 'static_pages#grep'
    get '/ispell', to: 'static_pages#ispell'
    get '/jed', to: 'static_pages#jed'
    get '/joe', to: 'static_pages#joe'
    get '/join', to: 'static_pages#join'
    get '/look', to: 'static_pages#look'
    get '/mtype', to: 'static_pages#mtype'
    get '/pico', to: 'static_pages#pico'
    get '/rgrep', to: 'static_pages#rgrep'
    get '/sed', to: 'static_pages#sed'
    get '/sort', to: 'static_pages#sort'
    get '/spell', to: 'static_pages#spell'
    get '/tr', to: 'static_pages#tr'
    get '/uniq', to: 'static_pages#uniq'
    get '/wc', to: 'static_pages#wc'
  #internet
    get '/apachectl',   to: 'static_pages#apachectl'
    get '/arpwatch', to: 'static_pages#arpwatch'
    get '/cu', to: 'static_pages#cu'
    get '/dip', to: 'static_pages#dip'
    get '/dnsconf', to: 'static_pages#dnsconf'
    get '/efax', to: 'static_pages#efax'
    get '/getty', to: 'static_pages#getty'
    get '/httpd', to: 'static_pages#httpd'
    get '/ifconfig', to: 'static_pages#ifconfig'
    get '/mesg', to: 'static_pages#mesg'
    get '/mingetty', to: 'static_pages#mingetty'
    get '/minicom', to: 'static_pages#minicom'
    get '/nc', to: 'static_pages#nc'
    get '/netconf', to: 'static_pages#netconf'
    get '/netconfig', to: 'static_pages#netconfig'
    get '/netstat', to: 'static_pages#netstat'
    get '/newaliases', to: 'static_pages#newaliases'
    get '/ping', to: 'static_pages#ping'
    get '/ppp-off', to: 'static_pages#ppp-off'
    get '/pppsetup', to: 'static_pages#pppsetup'
    get '/pppstats', to: 'static_pages#pppstats'
    get '/samba', to: 'static_pages#samba'
    get '/setserial', to: 'static_pages#setserial'
    get '/shapecfg', to: 'static_pages#shapecfg'
    get '/smbclient', to: 'static_pages#smbclient'
    get '/smbd', to: 'static_pages#smbd'
    get '/statserial', to: 'static_pages#statserial'
    get '/talk', to: 'static_pages#talk'
    get '/tcpdump', to: 'static_pages#tcpdump'
    get '/telnet', to: 'static_pages#telnet'
    get '/testparm', to: 'static_pages#testparm'
    get '/traceroute', to: 'static_pages#traceroute'
    get '/tty',       to: 'static_pages#tty'
    get '/uulog',     to: 'static_pages#uulog'
    get '/uuname',    to: 'static_pages#uuname'
    get '/uustat',    to: 'static_pages#uustat'
    get '/uux',    to: 'static_pages#uux'
    get '/wall',  to: 'static_pages#wall'
    get '/write',   to: 'static_pages#write'
    get '/ytalk',   to: 'static_pages#ytalk'
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end
